CREATE TABLE `game` (
  `id` CHAR(32),
  `gameday_link` CHAR(32),
  `time` CHAR(6),
  `ampm` CHAR(2),
  `day` CHAR(3),
  `league` CHAR(2),
  `game_type` CHAR(1),
  `home_division` CHAR(1),
  `away_division` CHAR(1),
  `gameday_sw` CHAR(1),
  `status` CHAR(32),
  `ind` CHAR(2),
  `inning` INTEGER,
  `outs` INTEGER,
  `top_inning` CHAR(1),
  `away_code` CHAR(3),
  `home_code` CHAR(3),
  `away_file_code` CHAR(8),
  `home_file_code` CHAR(8),
  `away_team_id` INTEGER,
  `home_team_id` INTEGER,
  `away_name_abbrev` CHAR(3),
  `home_name_abbrev` CHAR(3),
  `away_team_city` CHAR(16),
  `home_team_city` CHAR(16),
  `away_team_runs` INTEGER,
  `home_team_runs` INTEGER,
  `home_win` INTEGER,
  `home_loss` INTEGER,
  `away_win` INTEGER,
  `away_loss` INTEGER,
  `venue` CHAR(32),
  `game_pk` INTEGER,
  `time_zone` CHAR(2),
  `away_team_name` CHAR(16),
  `away_league_id` INTEGER,
  `away_sport_code` CHAR(3),
  `home_team_name` CHAR(16),
  `home_league_id` INTEGER,
  `home_sport_code` CHAR(4),
  `away_games_back` FLOAT,
  `home_games_back` FLOAT,
  `home_games_back_wildcard` FLOAT,
  `venue_w_chan_loc` CHAR(16),
  `away_team_hits` INTEGER,
  `home_team_hits` INTEGER,
  `away_team_errors` INTEGER,
  `home_team_errors` INTEGER,
  `away_games_back_wildcard` FLOAT,
  `home_preview_link` CHAR(32),
  `reason` CHAR(16),
  `tv_station` CHAR(16),
  `away_preview_link` CHAR(32),
  `away_time` CHAR(6),
  `away_time_zone` CHAR(4),
  `away_ampm` CHAR(2),
  `home_time` CHAR(6),
  `home_time_zone` CHAR(4),
  `home_ampm` CHAR(2),
  `venue_id` INTEGER,
  `scheduled_innings` INTEGER,
  `away_league_id_spring` INTEGER,
  `away_split_squad` CHAR(1),
  `home_league_id_spring` INTEGER,
  `home_split_squad` CHAR(1),
  `description` CHAR(16),
  `mlbtv_link` CHAR(32),
  `wrapup_link` CHAR(32),
  `resume_date` DATE,
  `series` CHAR(16),
  `series_num` INTEGER,
  `time_hm_lg` CHAR(6),
  `hm_lg_ampm` CHAR(2),
  `tz_hm_lg_gen` CHAR(4),
  `time_aw_lg` CHAR(6),
  `aw_lg_ampm` CHAR(2),
  `tz_aw_lg_gen` CHAR(4),
  `home_audio_link` CHAR(64),
  `away_audio_link` CHAR(64),
  `original_date` DATE,
  `time_zone_aw_lg` FLOAT,
  `time_zone_hm_lg` FLOAT,
  `game_data_directory` CHAR(16),
  `preview_link` CHAR(64),
  `ser_home_nbr` INTEGER,
  `ser_games` INTEGER,
  `postseason_tv_link` CHAR(64),
  `url_scoreboard` CHAR(128) NOT NULL,
  `date` DATE NOT NULL,
  `url` varchar(128) NOT NULL,
  `url_player` CHAR(128) NOT NULL
  
);



CREATE TABLE pitch (
   des CHAR(256),
   id INTEGER,
   type CHAR(1),
   tfs INTEGER,
   tfs_zulu TEXT,
   x FLOAT,
   y FLOAT,
   cc CHAR(256),
   mt CHAR(256),
   on_1b INTEGER,
   on_2b INTEGER,
   on_3b INTEGER,
   sv_id CHAR(128),
   start_speed float,
   end_speed FLOAT,
   sz_top FLOAT,
   sz_bot FLOAT,
   pfx_x FLOAT,
   pfx_z FLOAT,
   px FLOAT,
   pz FLOAT,
   x0 FLOAT,
   y0 FLOAT,
   z0 FLOAT,
   vx0 FLOAT,
   vy0 FLOAT,
   vz0 FLOAT,
   ax FLOAT,
   ay FLOAT,
   az FLOAT,
   break_y FLOAT,
   break_angle FLOAT,
   break_length FLOAT,
   pitch_type CHAR(4),
   type_confidence FLOAT,
   zone INTEGER,
   nasty INTEGER,
   spin_dir FLOAT,
   spin_rate FLOAT,
   num INTEGER NOT NULL,
   count CHAR(4) NOT NULL,
   url CHAR(120) NOT NULL

);

CREATE TABLE atbat (

   num INTEGER NOT NULL,
   b INTEGER,
   s INTEGER,
   o INTEGER,
   start_tfs INTEGER,
   start_tfs_zulu CHAR(50),
   batter INTEGER,
   stand CHAR(1),
   b_height  CHAR(32),
   pitcher INTEGER,
   p_throws CHAR(1),
   des  CHAR(200),
   event  CHAR(128),
   score CHAR(1),
   home_team_runs INTEGER,
   away_team_runs INTEGER,
   event2 CHAR(128),
   event3 CHAR(128),
   url CHAR(120) NOT NULL,
   event4 CHAR(128),
   inning INTEGER,
   top_inning  CHAR(32),
   batter_name CHAR(20),
   pitcher_name CHAR(20)

);

CREATE TABLE runner (

	id INTEGER,
	start CHAR(2),
	end CHAR(2),
	event CHAR(20),
	score INTEGER,
	rbi INTEGER,
	earned INTEGER,
	url CHAR(120) NOT NULL
	
);

CREATE TABLE player (

	id INTEGER,
	first CHAR(20),
	last CHAR(20),
	num INTEGER,
	boxname CHAR(20),
	rl CHAR(1),
	position CHAR(2),
	status CHAR(1),
	bat_order INTEGER,
	game_position CHAR(2),
	avg FLOAT,
	hr INTEGER,
	rbi INTEGER,
	wins INTEGER,
	losses INTEGER,
	era FLOAT,
	team_abbrev CHAR(3),
	team_id INTEGER,
	parent_team_abbrev CHAR(4),
	parent_team_id INTEGER,
	url_player CHAR(108) NOT NULL,
	url CHAR(120) NOT NULL
	
);
	
CREATE TABLE umpire (

	position ENUM('first','home','second','third') NOT NULL,
	name CHAR(50),
	id INTEGER,
	url_player CHAR(108) NOT NULL,
	url CHAR(120) NOT NULL
	
);

CREATE TABLE coach (

	position CHAR(30),
	first CHAR(20),
	last CHAR(20),
	id INTEGER,
	num INTEGER,
	url_player CHAR(108) NOT NULL,
	url CHAR(120) NOT NULL
	
);